# Generated by Django 5.2.6 on 2025-09-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('unit_price_p', models.IntegerField()),
                ('vat_rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('covers', models.IntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PAID', 'Paid')], default='OPEN', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal_p', models.IntegerField(default=0)),
                ('service_charge_p', models.IntegerField(default=0)),
                ('vat_total_p', models.IntegerField(default=0)),
                ('total_p', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(max_length=255)),
                ('amount_p', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tab')),
            ],
        ),
        migrations.CreateModel(
            name='TabItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('unit_price_p', models.IntegerField()),
                ('vat_rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat_p', models.IntegerField()),
                ('line_total_p', models.IntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menuitem')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.tab')),
            ],
        ),
    ]
